# Generated by Django 5.1.2 on 2025-04-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_me_job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Low_salary',
            new_name='low_salary',
        ),
    ]
