# Generated by Django 5.1.2 on 2025-04-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_me_job', '0002_rename_low_salary_job_low_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercvsector',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
