# Generated by Django 5.1.2 on 2025-04-09 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_choice', models.CharField(max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('image_1', models.URLField()),
                ('path_1', models.CharField(max_length=200)),
                ('image_2', models.URLField(blank=True, null=True)),
                ('path_2', models.CharField(blank=True, max_length=200, null=True)),
                ('name_1', models.CharField(blank=True, max_length=100, null=True)),
                ('name_2', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('views_num', models.PositiveIntegerField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
